[package]
name = "possum-emu"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true

[dependencies]

# used by the binary
bytemuck = "1"
memmap2 = "0.5"
sdl2 = { version = "0.35", features = ["static-link", "bundled"] }
clap = { version = "3", features = ["derive"] }
